/**
 * Full functionality of the footer is hidden
 * DO NOT EDIT THIS FILE
 * @param filePath - The path of the file to edit
 * @returns The footer component
 */
"use client";

import { Button } from "@/components/ui/button";
import { ThumbsUp, ThumbsDown, Github } from "lucide-react";

export default function DocsFooter({ filePath }: { filePath: string }) {

    return (
        <div className="w-full flex flex-col gap-6 my-8 p-6 bg-card border shadow-sm rounded-lg">
            <p className="font-semibold">这份文档对您有帮助吗？</p>
            <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                    <Button variant="outline">
                        <ThumbsUp />
                        <span>有用</span>
                    </Button>
                    <Button variant="outline">
                        <ThumbsDown />
                        <span>无用</span>
                    </Button>
                </div>
                <Button
                    variant="ghost"
                    size="sm"
                    className="gap-1.5 text-neutral-500"
                    onClick={() => window.open(`https://github.com/leolin4258/rwkvcn-docs/blob/main/content/${filePath}`, '_blank')}
                >
                    <Github className="w-4 h-4" />
                    编辑此页
                </Button>
            </div>
        </div>
    )
}