/**
 * Feedback API is hidden for security reasons.
 * DO NOT EDIT THIS FILE
 * @param req - The request object
 * @returns The response object
 */
export async function POST(req: Request) {
    return new Response('Feedback API is hidden for security reasons.');
}